apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratosvil-replica-app
  labels:
    app: kratosvil-replica-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratosvil-replica-app
  template:
    metadata:
      labels:
        app: kratosvil-replica-app
    spec:
      containers:
        - name: kratosvil-replica-app
          image: 805778285334.dkr.ecr.us-east-1.amazonaws.com/kratosvil-replica-app:latest
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
